use crate::node::prelude::*;
use crate::{element_attribute, element_struct, void_element_struct};
element_struct!(Html, html);
element_attribute!(Html, manifest, "manifest");
element_attribute!(Html, version, "version");
element_attribute!(Html, xmlns, "xmlns");
element_struct!(Head, head);
element_attribute!(Head, profile, "profile");
element_struct!(Title, title);
void_element_struct!(Base, base);
element_attribute!(Base, href, "href");
element_attribute!(Base, target, "target");
void_element_struct!(Link, link);
element_attribute!(Link, href, "href");
element_attribute!(Link, crossorigin, "crossorigin");
element_attribute!(Link, rel, "rel");
element_attribute!(Link, media, "media");
element_attribute!(Link, hreflang, "hreflang");
element_attribute!(Link, r#type, "type");
element_attribute!(Link, sizes, "sizes");
element_attribute!(Link, r#as, "as");
element_attribute!(Link, importance, "importance");
element_attribute!(Link, integrity, "integrity");
element_attribute!(Link, referrerpolicy, "referrerpolicy");
element_attribute!(Link, title, "title");
void_element_struct!(Meta, meta);
element_attribute!(Meta, name, "name");
element_attribute!(Meta, http_equiv, "http-equiv");
element_attribute!(Meta, content, "content");
element_attribute!(Meta, charset, "charset");
element_attribute!(Meta, scheme, "scheme");
element_struct!(Style, style);
element_attribute!(Style, media, "media");
element_attribute!(Style, nonce, "nonce");
element_attribute!(Style, r#type, "type");
element_attribute!(Style, scoped, "scoped");
element_attribute!(Style, title, "title");
element_struct!(Body, body);
element_attribute!(Body, onafterprint, "onafterprint");
element_attribute!(Body, onbeforeprint, "onbeforeprint");
element_attribute!(Body, onbeforeunload, "onbeforeunload");
element_attribute!(Body, onhashchange, "onhashchange");
element_attribute!(Body, onlanguagechange, "onlanguagechange");
element_attribute!(Body, onmessage, "onmessage");
element_attribute!(Body, onoffline, "onoffline");
element_attribute!(Body, ononline, "ononline");
element_attribute!(Body, onpagehide, "onpagehide");
element_attribute!(Body, onpageshow, "onpageshow");
element_attribute!(Body, onpopstate, "onpopstate");
element_attribute!(Body, onstorage, "onstorage");
element_attribute!(Body, onunload, "onunload");
element_attribute!(Body, alink, "alink");
element_attribute!(Body, background, "background");
element_attribute!(Body, bgcolor, "bgcolor");
element_attribute!(Body, bottommargin, "bottommargin");
element_attribute!(Body, leftmargin, "leftmargin");
element_attribute!(Body, link, "link");
element_attribute!(Body, onblur, "onblur");
element_attribute!(Body, onerror, "onerror");
element_attribute!(Body, onfocus, "onfocus");
element_attribute!(Body, onload, "onload");
element_attribute!(Body, onredo, "onredo");
element_attribute!(Body, onresize, "onresize");
element_attribute!(Body, onundo, "onundo");
element_attribute!(Body, rightmargin, "rightmargin");
element_attribute!(Body, text, "text");
element_attribute!(Body, topmargin, "topmargin");
element_attribute!(Body, vlink, "vlink");
element_struct!(Article, article);
element_struct!(Section, section);
element_struct!(Nav, nav);
element_struct!(Aside, aside);
element_struct!(H1, h1);
element_struct!(H2, h2);
element_struct!(H3, h3);
element_struct!(H4, h4);
element_struct!(H5, h5);
element_struct!(H6, h6);
element_struct!(Header, header);
element_struct!(Footer, footer);
element_struct!(Address, address);
element_struct!(P, p);
void_element_struct!(Hr, hr);
element_attribute!(Hr, align, "align");
element_attribute!(Hr, color, "color");
element_attribute!(Hr, noshade, "noshade");
element_attribute!(Hr, size, "size");
element_attribute!(Hr, width, "width");
element_struct!(Pre, pre);
element_attribute!(Pre, cols, "cols");
element_attribute!(Pre, width, "width");
element_attribute!(Pre, wrap, "wrap");
element_struct!(Blockquote, blockquote);
element_attribute!(Blockquote, cite, "cite");
element_struct!(Ol, ol);
element_attribute!(Ol, reversed, "reversed");
element_attribute!(Ol, start, "start");
element_attribute!(Ol, r#type, "type");
element_attribute!(Ol, compact, "compact");
element_struct!(Ul, ul);
element_attribute!(Ul, compact, "compact");
element_struct!(Li, li);
element_attribute!(Li, value, "value");
element_attribute!(Li, r#type, "type");
element_struct!(Dl, dl);
element_struct!(Dt, dt);
element_struct!(Dd, dd);
element_attribute!(Dd, nowrap, "nowrap");
element_struct!(Figure, figure);
element_struct!(Figcaption, figcaption);
element_struct!(Main, main);
element_struct!(Div, div);
element_struct!(A, a);
element_attribute!(A, href, "href");
element_attribute!(A, target, "target");
element_attribute!(A, download, "download");
element_attribute!(A, ping, "ping");
element_attribute!(A, rel, "rel");
element_attribute!(A, hreflang, "hreflang");
element_attribute!(A, r#type, "type");
element_attribute!(A, referrerpolicy, "referrerpolicy");
element_struct!(Em, em);
element_struct!(Strong, strong);
element_struct!(Small, small);
element_struct!(S, s);
element_struct!(Cite, cite);
element_struct!(Q, q);
element_attribute!(Q, cite, "cite");
element_struct!(Dfn, dfn);
element_struct!(Abbr, abbr);
element_struct!(Ruby, ruby);
element_struct!(Rb, rb);
element_struct!(Rt, rt);
element_struct!(Rp, rp);
element_struct!(Time, time);
element_attribute!(Time, datetime, "datetime");
element_struct!(Code, code);
element_struct!(Var, var);
element_struct!(Samp, samp);
element_struct!(Kbd, kbd);
element_struct!(Sub, sub);
element_struct!(Sup, sup);
element_struct!(I, i);
element_struct!(B, b);
element_struct!(U, u);
element_struct!(Mark, mark);
element_struct!(Bdi, bdi);
element_struct!(Bdo, bdo);
element_attribute!(Bdo, dir, "dir");
element_struct!(Span, span);
void_element_struct!(Br, br);
element_attribute!(Br, clear, "clear");
void_element_struct!(Wbr, wbr);
element_struct!(Ins, ins);
element_attribute!(Ins, cite, "cite");
element_attribute!(Ins, datetime, "datetime");
element_struct!(Del, del);
element_attribute!(Del, cite, "cite");
element_attribute!(Del, datetime, "datetime");
element_struct!(Picture, picture);
void_element_struct!(Img, img);
element_attribute!(Img, alt, "alt");
element_attribute!(Img, src, "src");
element_attribute!(Img, srcset, "srcset");
element_attribute!(Img, crossorigin, "crossorigin");
element_attribute!(Img, usemap, "usemap");
element_attribute!(Img, ismap, "ismap");
element_attribute!(Img, width, "width");
element_attribute!(Img, height, "height");
element_attribute!(Img, decoding, "decoding");
element_attribute!(Img, loading, "loading");
element_attribute!(Img, referrerpolicy, "referrerpolicy");
element_attribute!(Img, sizes, "sizes");
element_attribute!(Img, importance, "importance");
element_attribute!(Img, intrinsicsize, "intrinsicsize");
element_struct!(Iframe, iframe);
element_attribute!(Iframe, src, "src");
element_attribute!(Iframe, srcdoc, "srcdoc");
element_attribute!(Iframe, name, "name");
element_attribute!(Iframe, sandbox, "sandbox");
element_attribute!(Iframe, seamless, "seamless");
element_attribute!(Iframe, allowfullscreen, "allowfullscreen");
element_attribute!(Iframe, width, "width");
element_attribute!(Iframe, height, "height");
element_attribute!(Iframe, allow, "allow");
element_attribute!(Iframe, allowpaymentrequest, "allowpaymentrequest");
element_attribute!(Iframe, csp, "csp");
element_attribute!(Iframe, importance, "importance");
element_attribute!(Iframe, referrerpolicy, "referrerpolicy");
void_element_struct!(Embed, embed);
element_attribute!(Embed, src, "src");
element_attribute!(Embed, r#type, "type");
element_attribute!(Embed, width, "width");
element_attribute!(Embed, height, "height");
element_struct!(Object, object);
element_attribute!(Object, data, "data");
element_attribute!(Object, r#type, "type");
element_attribute!(Object, typemustmatch, "typemustmatch");
element_attribute!(Object, name, "name");
element_attribute!(Object, usemap, "usemap");
element_attribute!(Object, form, "form");
element_attribute!(Object, width, "width");
element_attribute!(Object, height, "height");
element_attribute!(Object, archive, "archive");
element_attribute!(Object, border, "border");
element_attribute!(Object, classid, "classid");
element_attribute!(Object, codebase, "codebase");
element_attribute!(Object, codetype, "codetype");
element_attribute!(Object, declare, "declare");
element_attribute!(Object, standby, "standby");
element_attribute!(Object, tabindex, "tabindex");
void_element_struct!(Param, param);
element_attribute!(Param, name, "name");
element_attribute!(Param, value, "value");
element_attribute!(Param, r#type, "type");
element_attribute!(Param, valuetype, "valuetype");
element_struct!(Video, video);
element_attribute!(Video, src, "src");
element_attribute!(Video, crossorigin, "crossorigin");
element_attribute!(Video, poster, "poster");
element_attribute!(Video, preload, "preload");
element_attribute!(Video, autoplay, "autoplay");
element_attribute!(Video, mediagroup, "mediagroup");
element_attribute!(Video, r#loop, "loop");
element_attribute!(Video, muted, "muted");
element_attribute!(Video, controls, "controls");
element_attribute!(Video, width, "width");
element_attribute!(Video, height, "height");
element_struct!(Audio, audio);
element_attribute!(Audio, src, "src");
element_attribute!(Audio, crossorigin, "crossorigin");
element_attribute!(Audio, preload, "preload");
element_attribute!(Audio, autoplay, "autoplay");
element_attribute!(Audio, mediagroup, "mediagroup");
element_attribute!(Audio, r#loop, "loop");
element_attribute!(Audio, muted, "muted");
element_attribute!(Audio, controls, "controls");
void_element_struct!(Source, source);
element_attribute!(Source, src, "src");
element_attribute!(Source, r#type, "type");
element_attribute!(Source, sizes, "sizes");
element_attribute!(Source, srcset, "srcset");
element_attribute!(Source, media, "media");
void_element_struct!(Track, track);
element_attribute!(Track, default, "default");
element_attribute!(Track, kind, "kind");
element_attribute!(Track, label, "label");
element_attribute!(Track, src, "src");
element_attribute!(Track, srclang, "srclang");
element_struct!(Map, map);
element_attribute!(Map, name, "name");
void_element_struct!(Area, area);
element_attribute!(Area, alt, "alt");
element_attribute!(Area, coords, "coords");
element_attribute!(Area, shape, "shape");
element_attribute!(Area, href, "href");
element_attribute!(Area, target, "target");
element_attribute!(Area, download, "download");
element_attribute!(Area, ping, "ping");
element_attribute!(Area, rel, "rel");
element_attribute!(Area, hreflang, "hreflang");
element_attribute!(Area, r#type, "type");
element_attribute!(Area, accesskey, "accesskey");
element_struct!(Table, table);
element_attribute!(Table, border, "border");
element_attribute!(Table, align, "align");
element_struct!(Caption, caption);
element_attribute!(Caption, align, "align");
element_struct!(Colgroup, colgroup);
element_attribute!(Colgroup, span, "span");
element_attribute!(Colgroup, align, "align");
void_element_struct!(Col, col);
element_attribute!(Col, span, "span");
element_attribute!(Col, align, "align");
element_struct!(Tbody, tbody);
element_attribute!(Tbody, align, "align");
element_struct!(Thead, thead);
element_attribute!(Thead, align, "align");
element_struct!(Tfoot, tfoot);
element_attribute!(Tfoot, align, "align");
element_struct!(Tr, tr);
element_attribute!(Tr, align, "align");
element_struct!(Td, td);
element_attribute!(Td, colspan, "colspan");
element_attribute!(Td, rowspan, "rowspan");
element_attribute!(Td, headers, "headers");
element_attribute!(Td, abbr, "abbr");
element_attribute!(Td, align, "align");
element_attribute!(Td, axis, "axis");
element_attribute!(Td, bgcolor, "bgcolor");
element_struct!(Th, th);
element_attribute!(Th, colspan, "colspan");
element_attribute!(Th, rowspan, "rowspan");
element_attribute!(Th, headers, "headers");
element_attribute!(Th, scope, "scope");
element_attribute!(Th, sorted, "sorted");
element_attribute!(Th, abbr, "abbr");
element_attribute!(Th, align, "align");
element_attribute!(Th, axis, "axis");
element_attribute!(Th, bgcolor, "bgcolor");
element_struct!(Form, form);
element_attribute!(Form, accept_charset, "accept-charset");
element_attribute!(Form, action, "action");
element_attribute!(Form, autocomplete, "autocomplete");
element_attribute!(Form, enctype, "enctype");
element_attribute!(Form, method, "method");
element_attribute!(Form, name, "name");
element_attribute!(Form, novalidate, "novalidate");
element_attribute!(Form, target, "target");
element_attribute!(Form, accept, "accept");
element_attribute!(Form, autocapitalize, "autocapitalize");
element_struct!(Label, label);
element_attribute!(Label, form, "form");
element_attribute!(Label, r#for, "for");
void_element_struct!(Input, input);
element_attribute!(Input, accept, "accept");
element_attribute!(Input, alt, "alt");
element_attribute!(Input, autocomplete, "autocomplete");
element_attribute!(Input, autofocus, "autofocus");
element_attribute!(Input, checked, "checked");
element_attribute!(Input, dirname, "dirname");
element_attribute!(Input, disabled, "disabled");
element_attribute!(Input, form, "form");
element_attribute!(Input, formaction, "formaction");
element_attribute!(Input, formenctype, "formenctype");
element_attribute!(Input, formmethod, "formmethod");
element_attribute!(Input, formnovalidate, "formnovalidate");
element_attribute!(Input, formtarget, "formtarget");
element_attribute!(Input, height, "height");
element_attribute!(Input, inputmode, "inputmode");
element_attribute!(Input, list, "list");
element_attribute!(Input, max, "max");
element_attribute!(Input, maxlength, "maxlength");
element_attribute!(Input, min, "min");
element_attribute!(Input, minlength, "minlength");
element_attribute!(Input, multiple, "multiple");
element_attribute!(Input, name, "name");
element_attribute!(Input, pattern, "pattern");
element_attribute!(Input, placeholder, "placeholder");
element_attribute!(Input, readonly, "readonly");
element_attribute!(Input, required, "required");
element_attribute!(Input, size, "size");
element_attribute!(Input, src, "src");
element_attribute!(Input, step, "step");
element_attribute!(Input, r#type, "type");
element_attribute!(Input, value, "value");
element_attribute!(Input, width, "width");
element_struct!(Button, button);
element_attribute!(Button, autofocus, "autofocus");
element_attribute!(Button, disabled, "disabled");
element_attribute!(Button, form, "form");
element_attribute!(Button, formaction, "formaction");
element_attribute!(Button, formenctype, "formenctype");
element_attribute!(Button, formmethod, "formmethod");
element_attribute!(Button, formnovalidate, "formnovalidate");
element_attribute!(Button, formtarget, "formtarget");
element_attribute!(Button, name, "name");
element_attribute!(Button, r#type, "type");
element_attribute!(Button, value, "value");
element_attribute!(Button, autocomplete, "autocomplete");
element_struct!(Select, select);
element_attribute!(Select, autocomplete, "autocomplete");
element_attribute!(Select, autofocus, "autofocus");
element_attribute!(Select, disabled, "disabled");
element_attribute!(Select, form, "form");
element_attribute!(Select, multiple, "multiple");
element_attribute!(Select, name, "name");
element_attribute!(Select, required, "required");
element_attribute!(Select, size, "size");
element_struct!(Datalist, datalist);
element_struct!(Optgroup, optgroup);
element_attribute!(Optgroup, disabled, "disabled");
element_attribute!(Optgroup, label, "label");
element_struct!(Option, option);
element_attribute!(Option, disabled, "disabled");
element_attribute!(Option, label, "label");
element_attribute!(Option, selected, "selected");
element_attribute!(Option, value, "value");
element_struct!(Textarea, textarea);
element_attribute!(Textarea, autocomplete, "autocomplete");
element_attribute!(Textarea, autofocus, "autofocus");
element_attribute!(Textarea, cols, "cols");
element_attribute!(Textarea, dirname, "dirname");
element_attribute!(Textarea, disabled, "disabled");
element_attribute!(Textarea, form, "form");
element_attribute!(Textarea, inputmode, "inputmode");
element_attribute!(Textarea, maxlength, "maxlength");
element_attribute!(Textarea, minlength, "minlength");
element_attribute!(Textarea, name, "name");
element_attribute!(Textarea, placeholder, "placeholder");
element_attribute!(Textarea, readonly, "readonly");
element_attribute!(Textarea, required, "required");
element_attribute!(Textarea, rows, "rows");
element_attribute!(Textarea, wrap, "wrap");
element_attribute!(Textarea, autocapitalize, "autocapitalize");
element_attribute!(Textarea, spellcheck, "spellcheck");
element_struct!(Output, output);
element_attribute!(Output, r#for, "for");
element_attribute!(Output, form, "form");
element_attribute!(Output, name, "name");
element_struct!(Progress, progress);
element_attribute!(Progress, value, "value");
element_attribute!(Progress, max, "max");
element_struct!(Meter, meter);
element_attribute!(Meter, value, "value");
element_attribute!(Meter, min, "min");
element_attribute!(Meter, max, "max");
element_attribute!(Meter, low, "low");
element_attribute!(Meter, high, "high");
element_attribute!(Meter, optimum, "optimum");
element_attribute!(Meter, form, "form");
element_struct!(Fieldset, fieldset);
element_attribute!(Fieldset, disabled, "disabled");
element_attribute!(Fieldset, form, "form");
element_attribute!(Fieldset, name, "name");
element_struct!(Legend, legend);
element_struct!(Details, details);
element_attribute!(Details, open, "open");
element_struct!(Summary, summary);
element_struct!(Dialog, dialog);
element_attribute!(Dialog, open, "open");
element_struct!(Script, script);
element_attribute!(Script, src, "src");
element_attribute!(Script, r#type, "type");
element_attribute!(Script, charset, "charset");
element_attribute!(Script, r#async, "async");
element_attribute!(Script, defer, "defer");
element_attribute!(Script, crossorigin, "crossorigin");
element_attribute!(Script, nonce, "nonce");
element_attribute!(Script, integrity, "integrity");
element_attribute!(Script, nomodule, "nomodule");
element_attribute!(Script, referrerpolicy, "referrerpolicy");
element_attribute!(Script, text, "text");
element_struct!(Noscript, noscript);
element_struct!(Template, template);
element_struct!(Canvas, canvas);
element_attribute!(Canvas, width, "width");
element_attribute!(Canvas, height, "height");
element_attribute!(Canvas, moz_opaque, "moz-opaque");
element_struct!(Slot, slot);
element_attribute!(Slot, name, "name");
element_struct!(Data, data);
element_attribute!(Data, value, "value");
element_struct!(Hgroup, hgroup);
element_struct!(Menu, menu);
